sudo: false
language: "node_js"
node_js:
  - "4"
  - "6"
  - "7"
before_script:
script:
  - npm install istanbul
  - istanbul cover --print none --report none ./node_modules/.bin/_mocha
  # Test that running the executable itself does not create an error
  - bin/gql2ts-for-server.js
after_script:
  - ./.travis-ci/coverage.sh