sudo: false
language: "node_js"
node_js:
  - "4"
  - "6"
  - "7"
before_script:
script:
  - npm install istanbul remap-istanbul
  - istanbul cover --print none --report none ./node_modules/.bin/_mocha
  # Test that running the executable itself does not create an error
  - bin/graphql-typewriter.js
after_script:
  # This will fail in node v4, but it does not matter, because it is in 
  # after_script
  - remap-istanbul -i ./coverage/coverage.json -o ./coverage/coverage-remapped.json
  - istanbul report --include ./coverage/coverage-remapped.json text lcovonly
  - # Send to coveralls
  - npm install coveralls
  - cat ./coverage/lcov.info | coveralls 